<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 D:\bossnz\static\models\scene.gltf --root /models/ --types --printwidth 120 --precision 2
Author: The Cable Center (https://sketchfab.com/thecablecenter)
License: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
Source: https://sketchfab.com/3d-models/burger-king-man-f73fccfd8d46445eacc4bfc2d6ca5c72
Title: Burger King Man
-->

<script lang="ts">
  import type * as THREE from "three";
  import { Group } from "three";
  import {
    T,
    type Props,
    type Events,
    type Slots,
    forwardEventHandlers,
  } from "@threlte/core";
  import { useGltf } from "@threlte/extras";
  import { scaleFactor } from "$lib/stores/shares";

  type $$Props = Props<THREE.Group>;
  type $$Events = Events<THREE.Group>;
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

  export const ref = new Group();

  type GLTFResult = {
    nodes: {
      mesh_0: THREE.Mesh;
      mesh_1: THREE.Mesh;
    };
    materials: {
      material_0: THREE.MeshStandardMaterial;
    };
  };

  const gltf = useGltf<GLTFResult>("/models/scene.gltf");

  const component = forwardEventHandlers();

</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group
      rotation={[2.5, 1, 0.3]}
      scale={0.003 * $scaleFactor}
    >
      <T.Group position={[-35.08, -32.06, -46.84]}>
        <T.Mesh
          geometry={gltf.nodes.mesh_0.geometry}
          material={gltf.materials.material_0}
        />
        <T.Mesh
          geometry={gltf.nodes.mesh_1.geometry}
          material={gltf.materials.material_0}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
